version: '3'

services:
  fixmystreet:
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SUPERUSER_EMAIL: '${SUPERUSER_EMAIL}'
      SUPERUSER_PASSWORD: '${SUPERUSER_PASSWORD}'
    volumes:
      - ./conf/general.yml:/var/www/fixmystreet/fixmystreet/conf/general.yml
      - ./fixmybsresort-cobrand:/var/www/fixmystreet/cobrand
  postgres:
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:6.12
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  fixmystreet-pgdata:
  pgadmin-data: