version: '3'

services:
  fixmystreet:
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      SUPERUSER_EMAIL: '${SUPERUSER_EMAIL}'
      SUPERUSER_PASSWORD: '${SUPERUSER_PASSWORD}'
    volumes:
      - ./conf/general.yml:/var/www/fixmystreet/fixmystreet/conf/general.yml
      - ./fixmybsresort-cobrand:/var/www/fixmystreet/cobrand
  postgres:
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'